In [12]:
#import pandas and loading the dataset in to a dataframe
import pandas as pd 
df = pd.read_csv("data/DataCoSupplyChainDataset.csv", encoding = "latin1")

In [11]:
#(Rows, Columns) of the dataset
df.shape

(180519, 53)

In [9]:
#first 5 rows of the dataset
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [10]:
#column names and data types of the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [15]:
#missing values in the dataset
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
Customer Country                      0
Category Id                           0
Category Name                         0
Customer Fname                        0
Customer Email                        0
Customer Password                     0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Days for shipping (real)              0
Type                                  0
Department Id                         0
Customer Street                       0
Department Name                       0
Latitude                              0
Order City                            0
Order Country                         0
Longitude                             0
Market                                0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Customer Id                     0
order date (DateOrders)               0
Order Item Quantity                   0
Order Item Profit Ratio               0
Order Profit Per Order                0
Sales                                 0
Order Region                          0
Order State                           0
Order Status                          0
Order Item Total                      0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [19]:
#dropping the columns and updating the dataframe
cols_to_drop = ['Product Description','Order Zipcode', 'Product Image','Customer Password','Customer Email']
df = df.drop(columns=cols_to_drop)

In [20]:
df.shape

(180519, 48)

In [31]:
#remove
#1. whitespace
#2. lowercase
#3. remove currency symbol
#4. replace space with underscore

df.columns = (df.columns
                    .str.strip()
                    .str.lower()
                    .str.replace(r'[()]', '', regex=True)
                    .str.replace(r'\s+', '_', regex=True)
)

In [32]:
#rename columns
df = df.rename(columns={'order_date_dateorders': 'order_date', 'shipping_date_dateorders': 'shipping_date'})

In [33]:
df.columns.tolist()

['type',
 'days_for_shipping_real',
 'days_for_shipment_scheduled',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'product_card_id',
 'product_category_id',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date',
 'shipping_mode']

In [34]:
#convert order_date and shipping_date to datetime format
df['order_date'] = pd.to_datetime(df['order_date'])
df['shipping_date'] = pd.to_datetime(df['shipping_date'])

In [42]:
#calculating shipping duration in days
days_for_shipping_real = (df['shipping_date'] - df['order_date']).dt.days
days_for_shipment_scheduled = df['days_for_shipment_scheduled']

df['shipping_delay_days'] = days_for_shipping_real - days_for_shipment_scheduled
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month

for days in df['shipping_delay_days']:
    if days < 0:
        print("Early Delivery")
    elif days == 0:
        print("On Time Delivery")
    else:
        print("Late Delivery")

Early Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
On Time Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
On Time Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Early Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
On Time Delivery
On Time Delivery
Late Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery
On Time Delivery
On Time Delivery
On Time Delivery
Late Delivery
Late Delivery
On Time Delivery
Early Delivery
Early Delivery
Early Delivery
Late Delivery
Early Delivery
Early Delivery
Late Delivery
Late Delivery
Early Delivery
Late Delivery
Late Delivery
On Time Delivery
Late Delivery
Early Delivery
Late Delivery

In [ ]:
#viewing the first 5 rows of the relevant columns
df[['order_date', 'shipping_date', 'days_for_shipping_real',
    'days_for_shipment_scheduled', 'shipping_delay_days',
    'late_delivery_risk']].head(5)

,order_date,shipping_date,days_for_shipping_real,days_for_shipment_scheduled,shipping_delay_days,late_delivery_risk
0,2018-01-31 22:56:00,2018-02-03 22:56:00,3,4,-1,0
1,2018-01-13 12:27:00,2018-01-18 12:27:00,5,4,1,1
2,2018-01-13 12:06:00,2018-01-17 12:06:00,4,4,0,0
3,2018-01-13 11:45:00,2018-01-16 11:45:00,3,4,-1,0
4,2018-01-13 11:24:00,2018-01-15 11:24:00,2,4,-2,0

In [45]:
#calculated column
import numpy as np

#create conditions and choices for the new column
conditions = [
    df['shipping_delay_days'] < 0,
    df['shipping_delay_days'] == 0,
    df['shipping_delay_days'] > 0
]

#create choices for the new column
choices = [
    'Early Delivery',
    'On Time Delivery',
    'Late Delivery'
]

#create a new column 'delivery_performance' based on the conditions and choices
df['delivery_performance'] = np.select(conditions, choices, default='Unknown')

In [47]:
df[['order_date', 'shipping_date', 'days_for_shipping_real',
    'days_for_shipment_scheduled', 'shipping_delay_days',
    'late_delivery_risk', 'delivery_performance']].head(5)

,order_date,shipping_date,days_for_shipping_real,days_for_shipment_scheduled,shipping_delay_days,late_delivery_risk,delivery_performance
0,2018-01-31 22:56:00,2018-02-03 22:56:00,3,4,-1,0,Early Delivery
1,2018-01-13 12:27:00,2018-01-18 12:27:00,5,4,1,1,Late Delivery
2,2018-01-13 12:06:00,2018-01-17 12:06:00,4,4,0,0,On Time Delivery
3,2018-01-13 11:45:00,2018-01-16 11:45:00,3,4,-1,0,Early Delivery
4,2018-01-13 11:24:00,2018-01-15 11:24:00,2,4,-2,0,Early Delivery

In [48]:
#total number of orders for each delivery performance category
df['delivery_performance'].value_counts()

delivery_performance
Late Delivery       98743
Early Delivery      43366
On Time Delivery    38410
Name: count, dtype: int64

In [ ]:
#connect to sqlite database and create a table to store the data
import sqlite3

In [52]:
#save csv for power bi
df.to_csv('data/cleaned_supply_chain_data.csv', index=False)

In [53]:
#connect to sqlite database (creates deliveriq.db in your project root)
conn = sqlite3.connect('deliveriq.db')

In [ ]:
#save dataframe into sql table named 'orders'
df.to_sql('orders', conn, if_exists='replace', index=False)

C:\Users\Dulakshana\AppData\Local\Temp\ipykernel_107896\3844538888.py:2: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql('orders', conn, if_exists='replace', index=False)

180519

In [55]:
#verify in sql using pandas read_sql_query
test_query = "SELECT COUNT(*) AS total_orders FROM orders;"
pd.read_sql_query(test_query, conn)

   total_orders
0        180519

In [56]:
#an executive summary table showing:

#Each delivery_performance category ('Late Delivery', 'Early Delivery', 'On Time Delivery').
#The order_count (number of orders in each category).
#The percentage of total orders that each category represents, rounded to 2 decimal places.
#Sorted in descending order by order_count.
query = """
SELECT delivery_performance,
       COUNT(*) AS order_count,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS percentage
FROM orders
GROUP BY delivery_performance
ORDER BY order_count DESC
"""
pd.read_sql_query(query, conn)

  delivery_performance  order_count  percentage
0        Late Delivery        98743       54.70
1       Early Delivery        43366       24.02
2     On Time Delivery        38410       21.28

In [58]:
#We want to build a table grouped by shipping_mode showing:

#shipping_mode
#total_orders: Total count of orders.
#avg_scheduled_days: Average scheduled delivery days (rounded to 2 decimals).
#avg_actual_days: Average real delivery days (rounded to 2 decimals).
#avg_delay_days: Average delay duration (rounded to 2 decimals).
#late_rate_pct: Percentage of orders that were late (rounded to 2 decimals).
#Sorted from highest late rate to lowest (late_rate_pct DESC).

query = """
SELECT shipping_mode,
       COUNT(*) AS total_orders,
       ROUND(AVG(days_for_shipment_scheduled), 2) AS avg_scheduled_days,
       ROUND(AVG(days_for_shipping_real), 2) AS avg_actual_days,
       ROUND(AVG(shipping_delay_days), 2) AS avg_delay_days,
       ROUND(SUM(CASE WHEN shipping_delay_days > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS late_rate_pct
FROM orders
GROUP BY shipping_mode
ORDER BY late_rate_pct DESC
"""
pd.read_sql_query(query, conn)

,shipping_mode,total_orders,avg_scheduled_days,avg_actual_days,avg_delay_days,late_rate_pct
0,First Class,27814,1.0,2.00,1.00,100.00
1,Second Class,35216,2.0,3.99,1.99,79.73
2,Standard Class,107752,4.0,4.00,-0.00,39.77
3,Same Day,9737,0.0,0.48,0.00,0.00

In [59]:
#Write a query to display:

#order_region
#market
#total_orders: Count of orders
#total_sales: ROUND(SUM(sales), 2)
#avg_delay_days: ROUND(AVG(shipping_delay_days), 2)
#late_risk_pct: ROUND(AVG(late_delivery_risk) * 100.0, 2)
#Filter to keep only regions with COUNT(*) > 5000 using HAVING.
#Order by late_risk_pct DESC.

query = """
SELECT order_region,
       market,
       COUNT(*) AS total_orders,
       ROUND(SUM(sales), 2) AS total_sales,
       ROUND(AVG(shipping_delay_days), 2) AS avg_delay_days,
       ROUND(AVG(late_delivery_risk) * 100.0, 2) AS late_risk_pct
FROM orders
GROUP BY order_region, market
HAVING COUNT(*) > 5000
ORDER BY late_risk_pct DESC
"""
pd.read_sql_query(query, conn)

,order_region,market,total_orders,total_sales,avg_delay_days,late_risk_pct
0,South Asia,Pacific Asia,7731,1553680.92,0.57,56.27
1,Western Europe,Europe,27109,5894380.77,0.57,55.85
2,East of USA,USCA,6915,1371111.99,0.56,55.66
3,Southeast Asia,Pacific Asia,9539,1932495.57,0.54,55.53
4,West Asia,Pacific Asia,6009,1174671.78,0.55,55.28
5,US Center,USCA,5887,1151355.77,0.57,55.24
6,Central America,LATAM,28341,5665712.10,0.54,54.75
7,Southern Europe,Europe,9431,2047918.82,0.48,54.38
8,Eastern Asia,Pacific Asia,7280,1486401.34,0.54,54.33
9,South America,LATAM,14935,2960881.41,0.53,54.31
10,Northern Europe,Europe,9792,2155830.65,0.52,54.04
11,Oceania,Pacific Asia,10148,2016654.20,0.53,54.02
12,West of USA,USCA,7993,1571415.96,0.53,53.96
13,Caribbean,LATAM,8318,1651019.33,0.52,53.08

In [61]:
#Top 3 worst delayed product categories in each market
query = """
WITH category_delays AS (
    SELECT market,
           category_name,
           COUNT(*) AS total_orders,
           ROUND(AVG(shipping_delay_days), 2) AS avg_delay_days,
           ROUND(AVG(late_delivery_risk) * 100.0, 2) AS late_risk_pct,
           ROW_NUMBER() OVER (
               PARTITION BY market 
               ORDER BY AVG(late_delivery_risk) DESC
           ) AS rank_in_market
    FROM orders
    GROUP BY market, category_name
    HAVING COUNT(*) >= 100
)
SELECT market,
       category_name,
       total_orders,
       avg_delay_days,
       late_risk_pct,
       rank_in_market
FROM category_delays
WHERE rank_in_market <= 3;
"""

pd.read_sql_query(query, conn)

,market,category_name,total_orders,avg_delay_days,late_risk_pct,rank_in_market
0,Africa,Accessories,142,0.69,61.27,1
1,Africa,Electronics,249,0.65,56.22,2
2,Africa,Indoor/Outdoor Games,1318,0.59,55.92,3
3,Europe,Golf Gloves,294,0.78,62.93,1
4,Europe,Cameras,575,0.62,57.74,2
5,Europe,Books,308,0.45,57.14,3
6,LATAM,Baseball & Softball,203,0.61,59.61,1
7,LATAM,Boxing & MMA,127,0.67,59.06,2
8,LATAM,Lacrosse,124,0.56,58.06,3
9,Pacific Asia,Hockey,150,0.74,63.33,1
10,Pacific Asia,Baby,125,0.49,59.20,2
11,Pacific Asia,Pet Supplies,492,0.66,58.94,3
12,USCA,Trade-In,156,0.67,57.05,1
13,USCA,Electronics,553,0.52,56.42,2
14,USCA,Shop By Sport,1640,0.58,55.91,3